### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by rogermtnl** [SmartIdentity/smartId-contracts#9]
All the Tests are failing. Any specific steps to run before Running tests.
Contract: SmartIdentity
  Scenario: Alice has a current account with her bank, but wants to open an account for her business.
    1) Should create an identity for Alice so that she can create KYC attributes
  > No events were emitted
    2) Should create an identity for Alice's Retail Bank so they can endorse her KYC checks
  > No events were emitted
    3) Should create an identity for Alice's Commercial Bank so they can verify the KYC checks
  > No events were emitted
    4) Should allow Alice to create a new KYC attribute
  > No events were emitted
    5) Should allow Alice's Retail Bank to endorse Alice's KYC attribute
  > No events were emitted
    6) Should allow Alice to accept her Retail Bank's endorsement for her attribute
  > No events were emitted
    7) Should allow Alice's Bank to check that an endorsement exists for her KYC attribute; verifying her KYC checks
  > No events were emitted

0 passing (359ms)
7 failing

1) Contract: SmartIdentity Scenario: Alice has a current account with her bank, but wants to open an account for her busines
 Should create an identity for Alice so that she can create KYC attributes:
   ReferenceError: SmartIdentity is not defined
    at Context.<anonymous> (test\scenarios\alice.js:36:20)

2) Contract: SmartIdentity Scenario: Alice has a current account with her bank, but wants to open an account for her busines
 Should create an identity for Alice's Retail Bank so they can endorse her KYC checks:
   ReferenceError: SmartIdentity is not defined
    at Context.<anonymous> (test\scenarios\alice.js:54:20)

3) Contract: SmartIdentity Scenario: Alice has a current account with her bank, but wants to open an account for her busines
 Should create an identity for Alice's Commercial Bank so they can verify the KYC checks:
   ReferenceError: SmartIdentity is not defined
    at Context.<anonymous> (test\scenarios\alice.js:62:20)

4) Contract: SmartIdentity Scenario: Alice has a current account with her bank, but wants to open an account for her busines
 Should allow Alice to create a new KYC attribute:
   ReferenceError: SmartIdentity is not defined
    at Context.<anonymous> (test\scenarios\alice.js:70:20)

5) Contract: SmartIdentity Scenario: Alice has a current account with her bank, but wants to open an account for her busines
 Should allow Alice's Retail Bank to endorse Alice's KYC attribute:
   ReferenceError: SmartIdentity is not defined
    at Context.<anonymous> (test\scenarios\alice.js:77:20)

6) Contract: SmartIdentity Scenario: Alice has a current account with her bank, but wants to open an account for her busines
 Should allow Alice to accept her Retail Bank's endorsement for her attribute:
   ReferenceError: SmartIdentity is not defined
    at Context.<anonymous> (test\scenarios\alice.js:84:20)

7) Contract: SmartIdentity Scenario: Alice has a current account with her bank, but wants to open an account for her busines
 Should allow Alice's Bank to check that an endorsement exists for her KYC attribute; verifying her KYC checks:
   ReferenceError: SmartIdentity is not defined
    at Context.<anonymous> (test\scenarios\alice.js:91:20)

**Comment by rogermtnl** [comment]
We should we adding the var <ContractName> = require(<ContractName>) in all tests

**Comment by rogermtnl** [comment]
Resolved
